DROP DATABASE IF EXISTS `calendar`;
CREATE DATABASE IF NOT EXISTS `calendar`;
USE `calendar`;

CREATE TABLE `list` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
)

CREATE TABLE `birthdays` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`itemName` VARCHAR(255) NOT NULL,
	`day` TINYINT(4) NOT NULL,
	`month` TINYINT(4) NOT NULL,
	`time` SMALLINT(6) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);